services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shop_mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SilneHaslo123321!SilneHaslo123321!
    ports:
      - "1433:1433"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SilneHaslo123321!SilneHaslo123321!' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shop_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  productservice:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: shop_productservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # connection string do MSSQL w docker network
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=ProductDb;User Id=sa;Password=SilneHaslo123321!SilneHaslo123321!;TrustServerCertificate=True;
    ports:
      - "5144:8080"
    depends_on:
      mssql:
        condition: service_healthy
    restart: always

  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: shop_orderservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=OrderDb;User Id=sa;Password=SilneHaslo123321!SilneHaslo123321!;TrustServerCertificate=True;
      # ważne: w kontenerach NIE używamy localhost do product/rabbit
      - ProductClient__BaseUrl=http://productservice:8080/
      - Rabbit__Host=rabbitmq
      - Rabbit__User=guest
      - Rabbit__Pass=guest
    ports:
      - "5143:8080"
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      productservice:
        condition: service_started
    restart: always

  paymentservice:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    container_name: shop_paymentservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Rabbit__Host=rabbitmq
      - Rabbit__User=guest
      - Rabbit__Pass=guest
    ports:
      - "5145:8080"
    depends_on:
      rabbitmq:
        condition: service_started
    restart: always
